name: build-static-binary-manager-image
on: push
jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: clean to default
        run: sed -i 's/https:\/\/secflow.819819.xyz//g'   ./api/base.ts

      - name: cat packageService.ts
        run: cat ./api/base.ts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend-image
        uses: docker/build-push-action@v5
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            runshine0819/secflow-frontend:latest
            ghcr.io/runshine/secflow-frontend:latest
          file: ./docker/docker.txt

        

        